# Application Properties
spring.application.name=ResumeBuilder
spring.profiles.active=prod

spring.devtools.restart.enabled=true
eksconfiguration.enabled=true

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=215MB
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
feign.hystrix.enabled: true
hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
server.servlet.context-path=/resume/builder/backend/
spring.lifecycle.timeout-per-shutdown-phase=30s


